name: Java CI - Build on Push

on:
  push:
    branches:
      - fix-v2101.1.10
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Upload jars
        uses: actions/upload-artifact@v4
        with:
          name: ftb-teams-build
          path: |
            **/build/libs/*.jar
